### ISSUE TITLE
이용내역 확인 불가.

### ISSUE THREAD

**Issue by nibaboojit** [dcblock/DCCaffeKiosk#15]
### 환경
사용자 : 김경태
핸드폰 : 삼성 갤럭시 노트 9

### 증상 
1. 카페 키오스크에서 이용내역 확인
2. 네이버 앱으로 QR코드 스캔
3. 페이지가 유효하지 않습니다.(http://manager.digicaps.com/my_order/19b2dce4-b304-419d-ba8d-29e970e93207)

### 비고
정병옥 차장님과 함께 확인.
정병옥 차장님 이용내역은 확인 가능.
김경태 이용내역은 정병옥 차장님 폰으로도 확인 불가.(동일 메시지)

**Comment by bojung-dev** [comment]
네이버 앱에서만 같은 현상이 나타나는것 같습니다.
네이버 앱에서도 동작하도록 확인 하겠습니다.
문제가 해결되면 이슈는 닫겠습니다.

**Comment by bojung-dev** [comment]
네이버앱에서 2번의 URL 호출로 인하여 1회성 URL이 두번째 호출시 만료되는 현상이 발생한다.
네이버앱만의 특성으로 네이버앱에 대한 지원은 보류한다.
