### ISSUE TITLE
메뉴에 핫초코가 없어요!

### ISSUE THREAD

**Issue by nibaboojit** [dcblock/DCCaffeKiosk#17]
추가해주세요!
혹시 이런 피드백 작성하는 대표 페이지가 있나요?

**Comment by bojung-dev** [comment]
https://github.com/dcblock/wiki/issues
가 최상위 이슈 등록 페이지라고 생각하면 좋을것 같습니다.

핫초코는 경본에서 메뉴를 등록해 놓지 않았는데, 핫초코 메뉴 추가에 대한 요청을 경본에 하겠습니다.
